<?php

namespace ContainerHlQhQ8A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDevisControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NI3GIqK.App\Controller\DevisController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NI3GIqK.App\\Controller\\DevisController::delete()'] = ($container->privates['.service_locator.NI3GIqK'] ?? $container->load('get_ServiceLocator_NI3GIqKService'))->withContext('App\\Controller\\DevisController::delete()', $container);
    }
}
