<?php

namespace ContainerHlQhQ8A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaillerControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kCWfP_F.App\Controller\TaillerController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kCWfP_F.App\\Controller\\TaillerController::delete()'] = ($container->privates['.service_locator.kCWfP_F'] ?? $container->load('get_ServiceLocator_KCWfPFService'))->withContext('App\\Controller\\TaillerController::delete()', $container);
    }
}
