<?php

namespace ContainerHlQhQ8A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaillerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7zeOOMt.App\Entity\Tailler' shared service.
     *
     * @return \App\Entity\Tailler
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.7zeOOMt": it needs an instance of "App\\Entity\\Tailler" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
