<?php

namespace ContainerFCGaw8R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TYRiWvhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tYRiWvh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tYRiWvh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'haieRepository' => ['privates', 'App\\Repository\\HaieRepository', 'getHaieRepositoryService', true],
        ], [
            'haieRepository' => 'App\\Repository\\HaieRepository',
        ]);
    }
}
