<?php

namespace ContainerFCGaw8R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDevisControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tYRiWvh.App\Controller\DevisController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tYRiWvh.App\\Controller\\DevisController::index()'] = ($container->privates['.service_locator.tYRiWvh'] ?? $container->load('get_ServiceLocator_TYRiWvhService'))->withContext('App\\Controller\\DevisController::index()', $container);
    }
}
