<?php

namespace ContainerRHHuP5W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NI3GIqKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NI3GIqK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NI3GIqK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'devi' => ['privates', '.errored..service_locator.NI3GIqK.App\\Entity\\Devis', NULL, 'Cannot autowire service ".service_locator.NI3GIqK": it needs an instance of "App\\Entity\\Devis" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'devi' => 'App\\Entity\\Devis',
            'entityManager' => '?',
        ]);
    }
}
