<?php

namespace ContainerRHHuP5W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDevisControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XyKmQoN.App\Controller\DevisController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XyKmQoN.App\\Controller\\DevisController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'devi' => ['privates', '.errored..service_locator.XyKmQoN.App\\Entity\\Devis', NULL, 'Cannot autowire service ".service_locator.XyKmQoN": it needs an instance of "App\\Entity\\Devis" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'devi' => 'App\\Entity\\Devis',
        ]))->withContext('App\\Controller\\DevisController::show()', $container);
    }
}
