<?php

namespace ContainerX44KBbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KCWfPFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kCWfP_F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kCWfP_F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tailler' => ['privates', '.errored..service_locator.kCWfP_F.App\\Entity\\Tailler', NULL, 'Cannot autowire service ".service_locator.kCWfP_F": it needs an instance of "App\\Entity\\Tailler" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'tailler' => 'App\\Entity\\Tailler',
            'entityManager' => '?',
        ]);
    }
}
