<?php

namespace ContainerX44KBbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i9YOweH.App\Controller\CategorieController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i9YOweH.App\\Controller\\CategorieController::delete()'] = ($container->privates['.service_locator.i9YOweH'] ?? $container->load('get_ServiceLocator_I9YOweHService'))->withContext('App\\Controller\\CategorieController::delete()', $container);
    }
}
