<?php

namespace ContainerX44KBbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDevisService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NI3GIqK.App\Entity\Devis' shared service.
     *
     * @return \App\Entity\Devis
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.NI3GIqK": it needs an instance of "App\\Entity\\Devis" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
