<?php

namespace ContainerX44KBbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDevisControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s8rI1sG.App\Controller\DevisController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s8rI1sG.App\\Controller\\DevisController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'devisRepository' => ['privates', 'App\\Repository\\DevisRepository', 'getDevisRepositoryService', true],
        ], [
            'devisRepository' => 'App\\Repository\\DevisRepository',
        ]))->withContext('App\\Controller\\DevisController::index()', $container);
    }
}
