<?php

namespace ContainerX44KBbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaillerControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7zeOOMt.App\Controller\TaillerController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7zeOOMt.App\\Controller\\TaillerController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tailler' => ['privates', '.errored..service_locator.7zeOOMt.App\\Entity\\Tailler', NULL, 'Cannot autowire service ".service_locator.7zeOOMt": it needs an instance of "App\\Entity\\Tailler" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'tailler' => 'App\\Entity\\Tailler',
        ]))->withContext('App\\Controller\\TaillerController::show()', $container);
    }
}
