<?php

namespace ContainerX44KBbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaillerControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kCWfP_F.App\Controller\TaillerController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.kCWfP_F'] ?? $container->load('get_ServiceLocator_KCWfPFService'));

        if (isset($container->privates['.service_locator.kCWfP_F.App\\Controller\\TaillerController::edit()'])) {
            return $container->privates['.service_locator.kCWfP_F.App\\Controller\\TaillerController::edit()'];
        }

        return $container->privates['.service_locator.kCWfP_F.App\\Controller\\TaillerController::edit()'] = $a->withContext('App\\Controller\\TaillerController::edit()', $container);
    }
}
