<?php

namespace ContainerJr3FfMf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i9YOweH.App\Controller\CategorieController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.i9YOweH'] ?? $container->load('get_ServiceLocator_I9YOweHService'));

        if (isset($container->privates['.service_locator.i9YOweH.App\\Controller\\CategorieController::edit()'])) {
            return $container->privates['.service_locator.i9YOweH.App\\Controller\\CategorieController::edit()'];
        }

        return $container->privates['.service_locator.i9YOweH.App\\Controller\\CategorieController::edit()'] = $a->withContext('App\\Controller\\CategorieController::edit()', $container);
    }
}
