<?php

namespace ContainerJr3FfMf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaillerControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8dCnKBQ.App\Controller\TaillerController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8dCnKBQ.App\\Controller\\TaillerController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'taillerRepository' => ['privates', 'App\\Repository\\TaillerRepository', 'getTaillerRepositoryService', true],
        ], [
            'taillerRepository' => 'App\\Repository\\TaillerRepository',
        ]))->withContext('App\\Controller\\TaillerController::index()', $container);
    }
}
