<?php

namespace ContainerUlD3uqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AFZjVbRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aFZjVbR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aFZjVbR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\DevisController::index' => ['privates', '.service_locator.s8rI1sG.App\\Controller\\DevisController::index()', 'getDevisControllerindexService', true],
            'App\\Controller\\DevisController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\DevisController::new()', 'getDevisControllernewService', true],
            'App\\Controller\\DevisController::show' => ['privates', '.service_locator.XyKmQoN.App\\Controller\\DevisController::show()', 'getDevisControllershowService', true],
            'App\\Controller\\DevisController::edit' => ['privates', '.service_locator.NI3GIqK.App\\Controller\\DevisController::edit()', 'getDevisControllereditService', true],
            'App\\Controller\\DevisController::delete' => ['privates', '.service_locator.NI3GIqK.App\\Controller\\DevisController::delete()', 'getDevisControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\DevisController:index' => ['privates', '.service_locator.s8rI1sG.App\\Controller\\DevisController::index()', 'getDevisControllerindexService', true],
            'App\\Controller\\DevisController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\DevisController::new()', 'getDevisControllernewService', true],
            'App\\Controller\\DevisController:show' => ['privates', '.service_locator.XyKmQoN.App\\Controller\\DevisController::show()', 'getDevisControllershowService', true],
            'App\\Controller\\DevisController:edit' => ['privates', '.service_locator.NI3GIqK.App\\Controller\\DevisController::edit()', 'getDevisControllereditService', true],
            'App\\Controller\\DevisController:delete' => ['privates', '.service_locator.NI3GIqK.App\\Controller\\DevisController::delete()', 'getDevisControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\DevisController::index' => '?',
            'App\\Controller\\DevisController::new' => '?',
            'App\\Controller\\DevisController::show' => '?',
            'App\\Controller\\DevisController::edit' => '?',
            'App\\Controller\\DevisController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\DevisController:index' => '?',
            'App\\Controller\\DevisController:new' => '?',
            'App\\Controller\\DevisController:show' => '?',
            'App\\Controller\\DevisController:edit' => '?',
            'App\\Controller\\DevisController:delete' => '?',
        ]);
    }
}
