<?php

namespace ContainerUlD3uqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDevisControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NI3GIqK.App\Controller\DevisController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.NI3GIqK'] ?? $container->load('get_ServiceLocator_NI3GIqKService'));

        if (isset($container->privates['.service_locator.NI3GIqK.App\\Controller\\DevisController::edit()'])) {
            return $container->privates['.service_locator.NI3GIqK.App\\Controller\\DevisController::edit()'];
        }

        return $container->privates['.service_locator.NI3GIqK.App\\Controller\\DevisController::edit()'] = $a->withContext('App\\Controller\\DevisController::edit()', $container);
    }
}
