<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVY4xpzo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVY4xpzo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVY4xpzo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVY4xpzo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVY4xpzo\App_KernelDevDebugContainer([
    'container.build_hash' => 'VY4xpzo',
    'container.build_id' => '18ff8ee6',
    'container.build_time' => 1764660545,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVY4xpzo');
