<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX44KBbm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX44KBbm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX44KBbm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX44KBbm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX44KBbm\App_KernelDevDebugContainer([
    'container.build_hash' => 'X44KBbm',
    'container.build_id' => '3bf86232',
    'container.build_time' => 1765273343,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX44KBbm');
