<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHlQhQ8A\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHlQhQ8A/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHlQhQ8A.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHlQhQ8A\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHlQhQ8A\App_KernelDevDebugContainer([
    'container.build_hash' => 'HlQhQ8A',
    'container.build_id' => '9520b6d3',
    'container.build_time' => 1767606057,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHlQhQ8A');
